rahataid/rahat-ui

- apps/rahat-ui/src/sections/projects/c2c/beneficiary/useBeneficiaryColumns.tsx
- apps/rahat-ui/src/sections/projects/c2c/fundManagement/fundManagement.view.tsx
https://www.loom.com/share/c570faf1424e409bbca5c8e51c7922ef
> C2c Feedbacks

- apps/rahat-ui/src/sections/projects/rp/offlineManagement/details.table.tsx
- removed checkbox
https://github.com/rahataid/rahat-project-rp/issues/129
> removed checkbox

- apps/rahat-ui/src/sections/vendors/vendors.list.table.tsx
- apps/rahat-ui/src/sections/vendors/vendors.view.tsx
- disabled assigned project 
https://github.com/rahataid/rahat-project-rp/issues/122
> fix:disabled select project

- apps/rahat-ui/src/sections/projects/rp/disbursement-management/1-disbursement-plan.tsx
- apps/rahat-ui/src/sections/projects/rp/offlineManagement/setupBeneficiary/2-select-beneficiary.tsx
- apps/rahat-ui/src/sections/projects/rp/offlineManagement/setupBeneficiary/beneficiary-flow.tsx
- apps/rahat-ui/src/sections/projects/rp/offlineManagement/setupBeneficiary/select.beneficiary.table.tsx
- remove temporary pagination
- added manual pagination on disbursement and offlien management
-
https://github.com/rahataid/rahat-project-rp/issues/125
> Remove temporary pagination

- apps/rahat-ui/src/sections/beneficiary/beneficiaryDetail.tsx
- libs/query/src/lib/projects/projects.service.ts
- invalid single beneficary query on  assigning to project
https://github.com/rahataid/rahat-project-rp/issues/110
> Invalidate beneficiary on project assign 

- apps/rahat-ui/src/sections/projects/rp/campaigns/text/campaign.text.add.tsx
- make campaign type required
- make message required
https://github.com/rahataid/rahat-project-rp/issues/148
> Make field required in rp campaign

- apps/rahat-ui/src/sections/projects/rp/offlineManagement/setupBeneficiary/beneficiary-flow.tsx
- apps/rahat-ui/src/sections/projects/rp/offlineManagement/setupBeneficiary/confirm-page.tsx
- apps/rahat-ui/src/sections/projects/rp/vendors/vendors.detail.header.tsx
- libs/query/src/lib/rp/project-actions/actions.query.ts
- only fetch with flag beneficires synced false in offline management
- remove tooltip in close of vendor
https://github.com/rahataid/rahat-project-rp/issues/164
https://github.com/rahataid/rahat-project-rp/issues/120
> 164 disbale group

- apps/rahat-ui/src/sections/projects/rp/beneficiary/beneficiary.table.tsx
- apps/rahat-ui/src/sections/projects/rp/campaigns/text/campaign.text.add.tsx
- apps/rahat-ui/src/sections/projects/rp/campaigns/voice/campaign.voice.add.tsx
- added back arrow button on voice and text campaign
- set beneficary meta from project benefaciries meta
-
https://github.com/rahataid/rahat-project-rp/issues/120
> Added back button on voice and text campaign

- apps/rahat-ui/src/components/pagination.tsx
- apps/rahat-ui/src/sections/projects/rp/beneficiary/beneficiary.table.tsx
- apps/rahat-ui/src/sections/projects/rp/beneficiary/use.table.column.tsx
- apps/rahat-ui/src/sections/projects/rp/disbursement-management/1-disbursement-plan.tsx
- apps/rahat-ui/src/sections/projects/rp/disbursement-management/disburse-table.tsx
- apps/rahat-ui/src/sections/projects/rp/disbursement-management/group-assign-disbursement-amount.modal.tsx
- apps/rahat-ui/src/sections/projects/rp/disbursement-management/select.beneficiary.card.tsx
- apps/rahat-ui/src/sections/projects/rp/offlineManagement/setupBeneficiary/confirm-page.tsx
- apps/rahat-ui/src/sections/projects/rp/transactions/transactions.table.tsx
- apps/rahat-ui/src/sections/users/addUser.tsx
- fix beneficiary search by name
- filter by gender
- remove unused filter
- invalidate offline vendor query key after 10 second of setting up offline 
- fix pagination conflict on fund management
- ui fixes in assign token model
https://github.com/rahataid/rahat-project-rp/issues/44
https://github.com/rahataid/rahat-project-rp/issues/140
https://github.com/rahataid/rahat-project-rp/issues/130
> beneficiary filter

- apps/rahat-ui/src/sections/projects/rp/disbursement-management/disburse-table.tsx
> fix:fixed height of table

- apps/rahat-ui/src/sections/projects/c2c/beneficiary/beneficiary.detail.tsx
- apps/rahat-ui/src/sections/projects/c2c/beneficiary/beneficiary.table.tsx
- apps/rahat-ui/src/sections/projects/c2c/components/disburse-flow/1-disburse-method.tsx
- apps/rahat-ui/src/sections/projects/c2c/components/disburse-flow/2-disburse-amount.tsx
- apps/rahat-ui/src/sections/projects/c2c/components/disburse-flow/3-disburse-summary.tsx
- apps/rahat-ui/src/sections/projects/c2c/components/disburse-flow/disburse-flow.tsx
- apps/rahat-ui/src/sections/projects/c2c/fundManagement/fundManagement.view.tsx
- libs/query/src/lib/c2c/project-actions/actions.query.ts
C2c fixes & disburse flow updates.
> C2c Disburse Flow

- apps/rahat-ui/src/sections/beneficiary/groups/assignToProjectModal.tsx
- apps/rahat-ui/src/sections/beneficiary/groups/beneficiaryGroupDetail.tsx
- apps/rahat-ui/src/sections/projects/rp/campaigns/text/campaign.text.add.tsx
- apps/rahat-ui/src/sections/projects/rp/campaigns/text/campaigns.text.details.tsx
- apps/rahat-ui/src/sections/projects/rp/campaigns/text/confirm.modal.tsx
- apps/rahat-ui/src/sections/projects/rp/campaigns/text/text.log.details.tsx
- apps/rahat-ui/src/sections/projects/rp/campaigns/text/text.table.tsx
- apps/rahat-ui/src/sections/projects/rp/campaigns/text/useTextTableColumn.tsx
- libs/query/src/lib/rp/campaign/actions.query.ts
- integration of new rp connect
- disable assigned project
> fix:added rp connect

- apps/rahat-ui/src/sections/projects/rp/offlineManagement/details.table.tsx
- apps/rahat-ui/src/sections/projects/rp/offlineManagement/setupBeneficiary/beneficiary-flow.tsx
- apps/rahat-ui/src/sections/projects/rp/offlineManagement/setupBeneficiary/confirm-page.tsx
- apps/rahat-ui/src/sections/projects/rp/offlineManagement/table.tsx
- apps/rahat-ui/src/sections/projects/rp/vendors/vendors.detail.header.tsx
- apps/rahat-ui/src/sections/projects/rp/vendors/vendors.list.tsx
- set client side pagination on offline vendor details page
- error handeling on offline validation
-  fix refetch after setting offline
- refactor pagination on offline management table
-
> fix:fixed rp bugs

- apps/rahat-ui/src/sections/projects/rp/disbursement-management/1-disbursement-plan.tsx
- apps/rahat-ui/src/sections/projects/rp/disbursement-management/3-confirmation.tsx
- libs/query/src/lib/rp/project-actions/actions.query.ts
Merge only after merge in rp-project repo.
-action call updated as per new flow.(get the ben details through single action).
> integration updated as per new flow

- apps/rahat-ui/src/sections/projects/rp/campaigns/voice/campaign.voice.add.tsx
- apps/rahat-ui/src/sections/projects/rp/campaigns/voice/campaign.voice.details.tsx
- apps/rahat-ui/src/sections/projects/rp/campaigns/voice/confirm.moda.tsx
- apps/rahat-ui/src/sections/projects/rp/campaigns/voice/useVoiceTableColumn.tsx
- apps/rahat-ui/src/sections/projects/rp/campaigns/voice/voice.log.details.tsx
- apps/rahat-ui/src/sections/projects/rp/campaigns/voice/voice.table.tsx
- apps/rahat-ui/src/sections/projects/rp/offlineManagement/setupBeneficiary/confirm-page.tsx
> voice integration

- apps/rahat-ui/src/sections/beneficiary/beneficiary.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/beneficiary.detail.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/beneficiary.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/use.beneficiary.table.columns.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/communication/communication.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/communication/sms.detail.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/communication/use.sms.table.columns.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/offline-management/offline.management.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/offline-management/use.table.columns.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/offline-management/vendors.detail.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vendors/columns/use.vendors.table.columns.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vendors/vendors.detail.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vendors/vendors.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vouchers/confirmation.tsx
- apps/rahat-ui/src/sections/vendors/vendors.list.table.tsx
- added import beneficiary on core
- integrated beneficiary details page
- added communication logs and stats
> fix:fixes flow issue

- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/beneficiary.detail.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/beneficiary.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/communication/communication.sms.add.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vendors/columns/use.vendors.beneficiary.table.columns.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vendors/vendors.beneficiary.list.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vendors/vendors.detail.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vendors/vendors.view.tsx
- fix type in beneficiary details
- fix vendors beneficiary
- fix kenya transport
> fix:vendor beneficiary

- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/beneficiary.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/offline-management/select.vendor.multi.step.form.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vendors/vendors.beneficiary.list.tsx
- libs/query/src/lib/rp/offline/actions.query.ts
- fix beneficiary filters
- fix offline process
> fix:filter in beneficiary

- apps/rahat-ui/src/app/projects/el-kenya/[id]/beneficiary/import/page.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/beneficiary.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/import/beneficiary.import.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/import/import.beneficiary.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/import/index.ts
- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/use.beneficiary.table.columns.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/communication/communication.sms.add.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/communication/confirm.modal.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/communication/sms.detail.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/communication/use.sms.table.columns.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vouchers/beneficiary.view.tsx
- libs/query/src/lib/beneficiary/beneficiary.service.ts
- libs/query/src/lib/rp/campaign/actions.query.ts
- import beneficiary to project
- communication add groups
> benficiary assign to project

- apps/rahat-ui/src/sections/projects/cambodia/beneficiary/beneficiary.view.tsx
- apps/rahat-ui/src/sections/projects/cambodia/beneficiary/discarded.beneficiary.view.tsx
- apps/rahat-ui/src/sections/projects/cambodia/commission/commission.add.tsx
- apps/rahat-ui/src/sections/projects/cambodia/commission/commission.update.view.tsx
- libs/query/src/lib/projects/projects.service.ts
- cleanup of  commision scheme and updates
- disacarded benef integrtion
> Discarded benef list

- apps/rahat-ui/src/app/projects/el-kenya/[id]/beneficiary/group/[groupid]/page.tsx
- apps/rahat-ui/src/app/projects/el-kenya/[id]/beneficiary/group/[groupid]/select/page.tsx
- apps/rahat-ui/src/sections/beneficiary/groups/assignToProjectModal.tsx
- apps/rahat-ui/src/sections/beneficiary/groups/beneficiary-groups.view.tsx
- apps/rahat-ui/src/sections/chart-reports/datacard-wrapper.tsx
- apps/rahat-ui/src/sections/chart-reports/donut-wrapper.tsx
- apps/rahat-ui/src/sections/chart-reports/dynamic-reports.tsx
- apps/rahat-ui/src/sections/dashboard/dashboard.view.tsx
- apps/rahat-ui/src/sections/projects/components/project.layout.tsx
- apps/rahat-ui/src/sections/projects/components/project.nav.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/beneficiary.group.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/beneficiary.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/groups.detail.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/index.ts
- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/members.table.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/select.beneficiary.tsx
- ui of el-kenya project benficiaries
- ui of el-kenya project beneficiaries group
- integration of benficiary groups
https://jam.dev/c/75ad906a-287f-4b73-a6a6-77209fb0de7f
> fix:beneficiary groups integration

- apps/rahat-ui/src/sections/projects/el-kenya/vouchers/beneficiary.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vouchers/voucher-management-flow.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vouchers/warning.modal.tsx
- libs/query/src/lib/el-kenya/contracts/hooks/el-kenya.ts
- send phone number to send sms after after voucher assignment
- fix model not closing issue
> fix:send voucher sns

- apps/rahat-ui/src/sections/beneficiary/groups/assignToProjectModal.tsx
- apps/rahat-ui/src/sections/beneficiary/groups/beneficiary-groups.view.tsx
- apps/rahat-ui/src/sections/beneficiary/groups/group.create.tsx
- apps/rahat-ui/src/sections/beneficiary/groups/groups.detail.tsx
- apps/rahat-ui/src/sections/beneficiary/groups/members.table.tsx
- apps/rahat-ui/src/sections/beneficiary/groups/select.beneficiary.tsx
- libs/query/src/lib/beneficiary/beneficiary.service.ts
- core beneficiary group add integration
- group assign to project integration
- add beneficiary to group integration
> fix:core group integration

- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/beneficiary.group.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/beneficiary.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/select.beneficiary.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/communication/communication.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/communication/use.sms.table.columns.tsx
- fix beneficiary pagination
- fix beneficiary select pagination
- filter comunication logs according to app id
- fix phone number in communication logs
> fix:communication logs phone and logs filter

- apps/rahat-ui/src/sections/beneficiary/beneficiaryDetail.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/beneficiary.detail.tsx
- libs/query/src/lib/rp/project-actions/actions.query.ts
> fix:group details fix

- apps/rahat-ui/src/sections/projects/cambodia/beneficiary/beneficiary.detail.tsx
- apps/rahat-ui/src/sections/projects/cambodia/chw/chw.view.tsx
- apps/rahat-ui/src/sections/projects/cambodia/vendors/transaction.history.view.tsx
- apps/rahat-ui/src/sections/projects/cambodia/vendors/use.health.workers.table.columns.tsx
- apps/rahat-ui/src/sections/projects/cambodia/vendors/use.transaction.history.table.columns.tsx
- apps/rahat-ui/src/sections/projects/cambodia/vendors/vendors.details.tsx
- libs/query/src/lib/el-cambodia/subgraph/graph.query.ts
- libs/query/src/lib/el-cambodia/subgraph/subgraph.query.ts
- libs/query/src/lib/projects/projects.service.ts
1. Health worker details on VC details
2. Txn history on VC details a/c to tokenRedeem
3. Beneficiary stats on CHW home
> Cambodia integration 9

- apps/rahat-ui/src/sections/projects/el-kenya/communication/communication.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/communication/confirm.modal.tsx
- apps/rahat-ui/src/sections/users/addUser.tsx
> fix:add user validation

- apps/rahat-ui/src/sections/projects/el-kenya/vouchers/beneficiary.groups.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vouchers/confirmation.tsx
- fixed optional chaning
- fixed voucher assign
> Added optional chaining

- apps/rahat-ui/src/sections/projects/el-kenya/claim/claim.detail.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/claim/claim.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/claim/use.table.columns.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vouchers/vouchers.view.tsx
- libs/query/src/lib/el-kenya/project-actions/actions.query.ts
- libs/query/src/lib/rp/project-actions/actions.query.ts
-display the data in claim list 
-display the data in claim details
> [Merge tomorrow] Voucher stats

- apps/rahat-ui/src/app/projects/el-kenya/[id]/beneficiary/group/add/page.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/beneficiary.group.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/beneficiary.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/group.create.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/import/beneficiary.import.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/index.ts
- apps/rahat-ui/src/sections/projects/el-kenya/communication/communication.sms.add.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vouchers/beneficiary.groups.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vouchers/voucher-management-flow.tsx
- libs/query/src/lib/rp/campaign/actions.query.ts
- added group from project
- make remove communication transport from UI
- fixed beneficiary filter clear issue
> fixed kenya feedback

- apps/rahat-ui/src/sections/projects/el-kenya/communication/communication.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vendors/vendors.view.tsx
- fix logs phone number
- fix vendors search
> fix:fixed phone number

- apps/rahat-ui/src/sections/projects/el-kenya/communication/communication.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/communication/sms.detail.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/offline-management/select.vendor.multi.step.form.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/offline-management/use.vendors.table.columns.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/offline-management/vendors.detail.tsx
- show message in communication details page
- filter WALK_IN beneficiary in voucher management page
- vendor offline beneficiary search by phone
> fix:feedback

- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/beneficiary.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/group.create.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/groups.detail.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/use.beneficiary.table.columns.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/offline-management/beneficiary.groups.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/offline-management/select.vendor.multi.step.form.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/offline-management/step2.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/offline-management/use.vendors.table.columns.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vendors/columns/use.vendors.table.columns.tsx
- libs/query/src/lib/rp/project-actions/actions.query.ts
> List unsynced beneficiary groups in offline beneficiary groups

- apps/rahat-ui/src/sections/projects/el-kenya/communication/communication.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/offline-management/beneficiary.groups.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/offline-management/select.vendor.multi.step.form.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/offline-management/step2.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vendors/columns/use.vendors.beneficiary.table.columns.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vendors/vendors.beneficiary.list.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vendors/vendors.detail.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vendors/vendors.view.tsx
- communcation search fix
- offline beneficiary next button
- replace name with phone
> fix:fixes from feedback

- apps/rahat-ui/src/sections/beneficiary/groups/groups.detail.tsx
- apps/rahat-ui/src/sections/beneficiary/useBeneficiaryColumns.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/communication/communication.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/communication/sms.detail.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/offline-management/select.vendor.multi.step.form.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/offline-management/step2.tsx
- fixed typo
- added card in communication details
- fixed offline beneficiary pagination
> fix:fixed typo

- apps/rahat-ui/src/sections/vendors/useTableColumns.tsx
- apps/rahat-ui/src/sections/vendors/vendor.detail.tsx
- apps/rahat-ui/src/sections/vendors/vendors.detail.split.view.tsx
- apps/rahat-ui/src/sections/vendors/vendors.list.table.tsx
- libs/query/src/lib/vendors/vendors.service.ts
- vendor details page integration
- vendor filter
> fix:vendor issue

- apps/rahat-ui/src/app/projects/el-kenya/[id]/communication/edit/[cid]/page.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/import/beneficiary.import.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/communication/comms.manage.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/communication/communication.sms.edit.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/communication/index.ts
- libs/query/src/lib/rp/campaign/actions.query.ts
> fix:edit campaign

- apps/rahat-ui/src/sections/projects/el-kenya/offline-management/select.vendor.multi.step.form.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vouchers/beneficiary.groups.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vouchers/confirmation.tsx
- fetch groups without voucher in voucher manage page
> fix:voucher group fix

- apps/rahat-ui/src/sections/projects/cambodia/beneficiary/beneficiary.view.tsx
- apps/rahat-ui/src/sections/projects/cambodia/chw/chw.view.tsx
- apps/rahat-ui/src/sections/projects/cambodia/chw/use.chw.table.columns.tsx
- apps/rahat-ui/src/sections/projects/cambodia/commission/commission.payout.view.tsx
- apps/rahat-ui/src/sections/projects/cambodia/project.main.view.tsx
- columns for the health workers updated .
- rephrase the mistakes name .
> columns updated and rephrases in needed

- apps/rahat-ui/src/sections/projects/el-kenya/communication/sms.detail.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/offline-management/select.vendor.multi.step.form.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/offline-management/step2.tsx
- handle beneficary filter from backend in offline management
- make communication logs perPage default
> fix:changed api

- apps/rahat-ui/src/sections/projects/el-kenya/communication/comms.manage.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/communication/sms.detail.tsx
- communcation clinet side search
> fix:communication search

- apps/rahat-ui/src/app/projects/layout.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vendors/vendors.beneficiary.list.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vendors/vendors.detail.tsx
- show walkin and offline beneficiary in vendor details page
> fix:walkin beneficiary

- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/beneficiary.group.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/offline-management/beneficiary.groups.view.tsx
- libs/query/src/lib/rp/project-actions/actions.query.ts
- fix error while beneficiary groups is undefined
- added beneficiary groups pagination
> fix:fix error while group is undefined

- apps/rahat-ui/src/app/vendors/[id]/edit/page.tsx
- apps/rahat-ui/src/sections/vendors/index.ts
- apps/rahat-ui/src/sections/vendors/vendor.detail.tsx
- apps/rahat-ui/src/sections/vendors/vendor.edit.view.tsx
- apps/rahat-ui/src/sections/vendors/vendors.detail.split.view.tsx
- apps/rahat-ui/src/sections/vendors/vendors.layout.tsx
- apps/rahat-ui/src/sections/vendors/vendors.list.table.tsx
- libs/query/src/lib/vendors/vendors.service.ts
- Unassigned vendors can be updated and deleted.
- Assigned vendors cannot be deleted.
- Assigned vendors can be updated from the core, and the changes will also reflect on the project side.
> Vendors: update & delete

- apps/rahat-ui/src/sections/projects/el-kenya/vouchers/vouchers.view.tsx
- added not redeem vouchers stats on pie chart
- added redemption rate
- restructure pie chart and bar chart
> fix:fix voucher page reporting

- apps/rahat-ui/src/sections/projects/el-kenya/communication/comms.manage.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/communication/sms.detail.tsx
- libs/query/src/lib/rp/campaign/actions.query.ts
- added beneficiary count 
- campaign pagintion
> fix:Added beneficiary count

- apps/rahat-ui/src/sections/projects/comms/campaigns/ivr/campaign.ivr.add.tsx
> fix:removed select without value

- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/beneficiary.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vouchers/vouchers.view.tsx
- remove whitespace
- count not redeem by glass status
> fix:remove filter white space

- apps/rahat-ui/src/app/projects/c2c/[id]/beneficiary/group/[groupid]/page.tsx
- apps/rahat-ui/src/app/projects/c2c/[id]/beneficiary/group/[groupid]/select/page.tsx
- apps/rahat-ui/src/app/projects/c2c/[id]/beneficiary/group/add/page.tsx
- apps/rahat-ui/src/app/projects/c2c/[id]/communication/[cid]/page.tsx
- apps/rahat-ui/src/app/projects/c2c/[id]/communication/add/page.tsx
- apps/rahat-ui/src/app/projects/c2c/[id]/communication/edit/[cid]/page.tsx
- apps/rahat-ui/src/app/projects/c2c/[id]/communication/manage/page.tsx
- apps/rahat-ui/src/app/projects/c2c/[id]/communication/page.tsx
- apps/rahat-ui/src/sections/projects/c2c/beneficiary/beneficiary.group.view.tsx
- apps/rahat-ui/src/sections/projects/c2c/beneficiary/beneficiary.view.tsx
- apps/rahat-ui/src/sections/projects/c2c/beneficiary/group.create.tsx
- apps/rahat-ui/src/sections/projects/c2c/beneficiary/groups.detail.tsx
- apps/rahat-ui/src/sections/projects/c2c/beneficiary/index.ts
- apps/rahat-ui/src/sections/projects/c2c/beneficiary/select.beneficiary.tsx
- apps/rahat-ui/src/sections/projects/c2c/communication/comms.manage.tsx
- apps/rahat-ui/src/sections/projects/c2c/communication/communication.sms.add.tsx
- apps/rahat-ui/src/sections/projects/c2c/communication/communication.sms.edit.tsx
- apps/rahat-ui/src/sections/projects/c2c/communication/communication.view.tsx
- apps/rahat-ui/src/sections/projects/c2c/communication/confirm.modal.tsx
- apps/rahat-ui/src/sections/projects/c2c/communication/index.ts
- apps/rahat-ui/src/sections/projects/c2c/communication/sms.detail.tsx
- apps/rahat-ui/src/sections/projects/c2c/communication/use.sms.table.columns.tsx
- apps/rahat-ui/src/sections/projects/c2c/grievance/grievance.add.form.tsx
- apps/rahat-ui/src/sections/projects/c2c/table.component.tsx
- apps/rahat-ui/src/sections/projects/c2c/useNavItems.tsx
- apps/rahat-ui/src/sections/projects/components/members.table.tsx
- apps/rahat-ui/src/sections/projects/components/use.grouped.beneficiary.table.columns.tsx
- libs/query/src/lib/c2c/campaign/actions.query.ts
- libs/query/src/lib/c2c/project-actions/actions.query.ts
- created hooks for groups and communication
- added create,list and assigned to groups 
- migrated communication to new ui
> Added groups and new communication

- apps/rahat-ui/src/app/projects/c2c/[id]/beneficiary/group/add/page.tsx
- apps/rahat-ui/src/sections/projects/c2c/beneficiary/index.ts
- apps/rahat-ui/src/sections/projects/c2c/components/disburse-flow/1-disburse-method.tsx
- apps/rahat-ui/src/sections/projects/c2c/components/disburse-flow/disburse-flow.tsx
- remove kenya component getting used'
- filter disbursement method from setting
> fix:fixed component import error

- apps/rahat-ui/src/app/projects/c2c/[id]/beneficiary/import/page.tsx
- apps/rahat-ui/src/sections/projects/c2c/beneficiary/import/beneficiary.import.tsx
- apps/rahat-ui/src/sections/projects/c2c/beneficiary/import/index.ts
- apps/rahat-ui/src/sections/projects/c2c/grievance/grievance.add.form.tsx
- apps/rahat-ui/src/sections/projects/c2c/grievance/grievance.detail.tsx
- libs/query/src/lib/grievance/grievance.service.ts
- libs/query/src/lib/projects/projects.service.ts
- change grievance status
- import beneficiary
> fix:change grievance status

- apps/rahat-ui/src/sections/projects/c2c/edit/edit.form.tsx
- libs/query/src/lib/c2c/contracts/hooks/c2c.ts
- libs/query/src/lib/c2c/project-actions/actions.query.ts
> fix:disbursement status

- apps/rahat-ui/src/app/projects/comms/[id]/campaigns/text/manage/page.tsx
- apps/rahat-ui/src/sections/projects/comms/campaigns/ivr/campaign.ivr.details.tsx
- apps/rahat-ui/src/sections/projects/comms/campaigns/ivr/ivr.table.tsx
- apps/rahat-ui/src/sections/projects/comms/campaigns/text/campaign.text.add.tsx
- apps/rahat-ui/src/sections/projects/comms/campaigns/text/campaigns.text.details.tsx
- apps/rahat-ui/src/sections/projects/comms/campaigns/text/text.log.details.tsx
- apps/rahat-ui/src/sections/projects/comms/campaigns/text/text.table.old.tsx
- apps/rahat-ui/src/sections/projects/comms/campaigns/text/text.table.tsx
- apps/rahat-ui/src/sections/projects/comms/campaigns/voice/campaign.voice.add.tsx
- apps/rahat-ui/src/sections/projects/comms/campaigns/voice/campaign.voice.details.tsx
- apps/rahat-ui/src/sections/projects/comms/campaigns/voice/voice.table.tsx
- apps/rahat-ui/src/sections/projects/comms/campaigns/voice/voice.table_old.tsx
- apps/rahat-ui/src/sections/projects/comms/table.component.tsx
- apps/rahat-ui/src/sections/projects/comms/useTableColumn.tsx
- libs/query/src/lib/comms/campaign/actions.query.ts
- added communication logs
- filter voice and text campaign
> fix:added communication logs

- apps/rahat-ui/src/sections/projects/c2c/components/disburse-flow/disburse-flow.tsx
- disbaled button before selecting source and amount
> fix:disable button before source selected

- apps/rahat-ui/src/sections/projects/c2c/beneficiary/beneficiary.detail.tsx
- apps/rahat-ui/src/sections/projects/c2c/beneficiary/beneficiary.group.view.tsx
- apps/rahat-ui/src/sections/projects/c2c/beneficiary/useBeneficiaryColumns.tsx
- apps/rahat-ui/src/sections/projects/c2c/project.charts.tsx
- libs/query/src/lib/c2c/project-actions/actions.query.ts
- unique beneficiary in group
- make dashboard stats
> fix:added reporting

- apps/rahat-ui/src/sections/projects/c2c/beneficiary/beneficiary.detail.tsx
- apps/rahat-ui/src/sections/projects/c2c/beneficiary/useBeneficiaryColumns.tsx
- apps/rahat-ui/src/sections/projects/c2c/components/disburse-flow/2-disburse-amount.tsx
- apps/rahat-ui/src/sections/projects/c2c/components/disburse-flow/disburse-flow.tsx
- apps/rahat-ui/src/sections/projects/c2c/disbursement/transactions.table.tsx
- apps/rahat-ui/src/sections/projects/c2c/grievance/grievance.detail.tsx
- apps/rahat-ui/src/sections/projects/c2c/grievance/grievance.edit.tsx
- apps/rahat-ui/src/sections/projects/c2c/grievance/grievance.table.tsx
- apps/rahat-ui/src/sections/projects/c2c/grievance/useGrievanceColumn.tsx
- apps/rahat-ui/src/sections/projects/c2c/transactions/transactions.view.tsx
- apps/rahat-ui/src/sections/projects/c2c/transactions/utils/index.ts
- libs/query/src/lib/grievance/grievance.service.ts
- update the split view on grievance update
- general fixes from feedback
> fix:ui fixes from feedback

- apps/rahat-ui/src/sections/projects/el-kenya/vouchers/vouchers.view.tsx
> fix:fixed voucher page getting crashed

- apps/rahat-ui/src/sections/projects/c2c/beneficiary/beneficiary.table.tsx
- apps/rahat-ui/src/sections/projects/c2c/transactions/dataTableServerSidePagination.tsx
- libs/query/src/utils/use-pagination.ts
- added server side pagination
> fix:added server side pagination

- apps/rahat-ui/src/sections/projects/c2c/beneficiary/beneficiary.detail.tsx
- apps/rahat-ui/src/sections/projects/c2c/beneficiary/beneficiary.transaction.table.tsx
- apps/rahat-ui/src/sections/projects/c2c/beneficiary/beneficiary.view.tsx
- apps/rahat-ui/src/sections/projects/c2c/beneficiary/useBeneficiaryColumns.tsx
- apps/rahat-ui/src/sections/projects/c2c/communication/communication.sms.add.tsx
- apps/rahat-ui/src/sections/projects/c2c/communication/communication.view.tsx
- apps/rahat-ui/src/sections/projects/c2c/communication/use.sms.table.columns.tsx
- apps/rahat-ui/src/sections/projects/c2c/components/disburse-flow/2-disburse-amount.tsx
- apps/rahat-ui/src/sections/projects/c2c/components/disburse-flow/3-disburse-summary.tsx
- apps/rahat-ui/src/sections/projects/c2c/components/disburse-flow/disburse-flow.tsx
- libs/query/src/lib/c2c/campaign/actions.query.ts
- added usdc
- send transportid from client side
- fix logs pagination
> added transport from client

- apps/rahat-ui/src/sections/projects/c2c/beneficiary/beneficiary.detail.tsx
- apps/rahat-ui/src/sections/projects/c2c/beneficiary/useBeneficiaryColumns.tsx
> fix:change string to number

- apps/rahat-ui/src/sections/projects/c2c/communication/email/communication.sms.add.tsx
- apps/rahat-ui/src/sections/projects/c2c/communication/text/communication.sms.add.tsx
- remove transport name from env
> fix:added transport name in add campaign form

- apps/rahat-ui/src/sections/community-beneficiary/view.tsx
- apps/rahat-ui/src/sections/projects/c2c/communication/email/communication.sms.add.tsx
- apps/rahat-ui/src/sections/projects/c2c/components/disburse-flow/confirm.tsx
- apps/rahat-ui/src/sections/projects/c2c/components/disburse-flow/disburse-flow.tsx
- apps/rahat-ui/src/sections/projects/c2c/const.ts
- apps/rahat-ui/src/sections/projects/c2c/disbursement/approvals.table.tsx
- apps/rahat-ui/src/sections/projects/c2c/edit/edit.form.tsx
- apps/rahat-ui/src/sections/projects/c2c/grievance/grievance.add.form.tsx
- apps/rahat-ui/src/sections/projects/c2c/grievance/grievance.detail.tsx
- apps/rahat-ui/src/sections/projects/c2c/grievance/grievance.edit.tsx
- apps/rahat-ui/src/sections/projects/c2c/grievance/useGrievanceColumn.tsx
- libs/query/src/lib/c2c/contracts/hooks/c2c.ts
- libs/query/src/lib/c2c/project-actions/actions.query.ts
- changed sms text to email
- fixed issue in edit project
- change griverance status and fix edit
- fix disbursment amount
> fix:change email text

- apps/rahat-ui/src/sections/projects/c2c/transactions/transactions.view.tsx
- apps/rahat-ui/src/sections/projects/c2c/transactions/utils/index.ts
- libs/query/src/lib/c2c/contracts/hooks/c2c.ts
- added a safe wallet on multi-sig
- fixed type in disbursement amount
> Fixed build issue

- apps/rahat-ui/src/sections/projects/c2c/beneficiary/beneficiary.transaction.table.tsx
- apps/rahat-ui/src/sections/projects/c2c/communication/email/confirm.modal.tsx
- apps/rahat-ui/src/sections/projects/c2c/communication/text/confirm.modal.tsx
- apps/rahat-ui/src/sections/projects/c2c/components/disburse-flow/confirm.tsx
- apps/rahat-ui/src/sections/projects/c2c/disbursement/approvals.table.tsx
- apps/rahat-ui/src/sections/projects/c2c/edit/edit.form.tsx
- apps/rahat-ui/src/sections/projects/c2c/transactions/transactions.view.tsx
- apps/rahat-ui/src/sections/projects/c2c/transactions/types/index.ts
- apps/rahat-ui/src/sections/projects/c2c/transactions/useTransactionColumn.tsx
- apps/rahat-ui/src/sections/projects/c2c/transactions/utils/index.ts
- libs/query/src/lib/c2c/contracts/hooks/c2c.ts
- libs/query/src/lib/c2c/subgraph/graph.query.ts
- libs/query/src/lib/c2c/utils/index.ts
- query from in transfer
- fixed redirect issue
- fixed project type not showing in select
- fixed transaction amount  conversion
> C2C prod feedbackk

- .gitignore
- apps/rahat-ui/src/app/projects/aa/[id]/activities/[activityID]/page.tsx
- apps/rahat-ui/src/app/projects/aa/[id]/activities/list/[title]/page.tsx
- apps/rahat-ui/src/app/projects/aa/[id]/activities/page.tsx
- apps/rahat-ui/src/common/filtersTags.tsx
- apps/rahat-ui/src/common/index.ts
- apps/rahat-ui/src/common/spinner.loader.tsx
- apps/rahat-ui/src/constants/aa.constants.ts
- apps/rahat-ui/src/sections/projects/aa-2/activities/components/communicationCard.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/components/documentCard.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/components/phase-card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/components/phase-content.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/details/activity.communication.list.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/details/activity.detail.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/details/activity.detail.cards.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/details/activity.detail.page.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/details/activity.payout.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/details/update.activity.status.dialog.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/index.ts
- apps/rahat-ui/src/sections/projects/aa-2/activities/list/activities.list.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/list/activities.table.filters.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/list/activities.table.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/list/useActivitiesTableColumn.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/main.tsx
- apps/rahat-ui/src/utils/index.ts
- apps/rahat-ui/src/utils/prev.pagination.storage.ts
- libs/query/src/lib/aa/activities/activities.service.ts
activity details design only as the  integration is halt due to server not deployedd of aa-project as the communication part is integrated.
> Activities design integration

- apps/rahat-ui/src/app/projects/layout.tsx
- apps/rahat-ui/src/sections/projects/components/project.layout.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/offline-management/beneficiary.groups.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/offline-management/step2.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vouchers/vouchers.manage.tsx
- show error message while wallet is not connected
- throw to login page from project if user is unauthorized
- fixed checked in offline group
> fix:fixed from feedback

- apps/rahat-ui/src/sections/projects/el-kenya/card.pagination.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/offline-management/beneficiary.groups.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vouchers/beneficiary.groups.view.tsx
- group pagination in offine beneficiary and voucher page
> fix:group pagination

- apps/rahat-ui/src/app/projects/aa/[id]/communication-logs/[commsIdXactivityIdXsessionId]/page.tsx
- apps/rahat-ui/src/app/projects/aa/[id]/communication-logs/commsdetails/[commsIdXactivityIdXsessionId]/page.tsx
- apps/rahat-ui/src/app/projects/aa/[id]/communication-logs/details/[activityId]/page.tsx
- apps/rahat-ui/src/app/projects/aa/[id]/communication-logs/page.tsx
- apps/rahat-ui/src/common/index.ts
- apps/rahat-ui/src/common/select.component.tsx
- apps/rahat-ui/src/common/spinner.loader.tsx
- apps/rahat-ui/src/sections/projects/aa-2/communicationLog/details/comms.logs.detail.page.tsx
- apps/rahat-ui/src/sections/projects/aa-2/communicationLog/details/communication.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/communicationLog/details/view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/communicationLog/index.ts
- apps/rahat-ui/src/sections/projects/aa-2/communicationLog/main.tsx
- apps/rahat-ui/src/sections/projects/aa-2/communicationLog/table/comms.activities.table.tsx
- apps/rahat-ui/src/sections/projects/aa-2/communicationLog/table/comms.logs.table.tsx
- apps/rahat-ui/src/sections/projects/aa-2/communicationLog/table/useCommsActivitesTableColumns.tsx
- apps/rahat-ui/src/sections/projects/aa-2/communicationLog/table/useCommsLogsTableColumns.tsx
- apps/rahat-ui/src/sections/projects/aa/useAANavItems.tsx
[Issue](https://github.com/rahataid/rahat-project-aa/issues/356)
> Aa comms UI

- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/automated.trigger.add.form.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/dynamic.triggers.list.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/trigger.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/triggers.list.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/triggers.list.tabs.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/detail.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/edit.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/phase.detail.tsx
- libs/query/src/lib/aa/phases/phases.service.ts
- libs/query/src/lib/aa/trigger-statements/trigger-statements.service.ts
https://github.com/rahataid/rahat-project-aa/issues/358
> Refine trigger statement ui

- apps/rahat-ui/src/sections/projects/aa-2/activities/add/add.activity.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/add/add.communication.form.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/components/phase-card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/components/phase-content.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/details/activity.detail.page.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/edit/activity.edit.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/main.tsx
[issue](https://github.com/rahataid/rahat-project-aa/issues/360)
> Aa feedback activities

- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dhm/info.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dhm/input.calendar.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dhm/rainfall.watch.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dhm/river.watch.map.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dhm/river.watch.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dhm/water.level.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/river.watch.details.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/add.trigger.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/dynamic.triggers.list.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/trigger.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/detail.tsx
- libs/query/src/lib/aa/trigger-statements/trigger-statements.service.ts
https://github.com/rahataid/rahat-project-aa/issues/359
> AA : FE Fixes

- apps/rahat-ui/src/sections/projects/components/project.layout.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/communication/communication.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/communication/sms.detail.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/communication/use.sms.table.columns.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vendors/vendors.detail.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vendors/vendors.view.tsx
- apps/rahat-ui/src/sections/projects/sms-voucher/beneficiary/beneficiary.view.tsx
- apps/rahat-ui/src/sections/projects/sms-voucher/select.component.tsx
- libs/query/src/lib/rp/campaign/actions.query.ts
- added server side pagination in communication
- modified select component 
- fixed vendor details
> fix:kenya feedback

- apps/rahat-ui/src/sections/projects/aa-2/activities/add/add.activity.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/add/add.communication.form.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/edit/activity.edit.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dhm/rainfall.monitor.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dhm/rainfall.watch.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dhm/river.watch.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/detail.tsx
[issue](https://github.com/rahataid/rahat-project-aa/issues/361)
> Rainfall UI integration

- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/beneficiary.group.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/beneficiary.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/select.beneficiary.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/claim/claim.detail.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/claim/claim.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/communication/communication.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/communication/sms.detail.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/offline-management/beneficiary.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/offline-management/offline.management.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/offline-management/select.vendor.multi.step.form.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/offline-management/step1.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/transactions/transactions.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vendors/vendors.detail.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vouchers/beneficiary.groups.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vouchers/beneficiary.view.tsx
- apps/rahat-ui/src/sections/projects/sms-voucher/beneficiary/beneficiary.view.tsx
- fixed loader in kenya tables
> fix:fixed loader

- apps/rahat-ui/src/components/dataCard.tsx
- apps/rahat-ui/src/sections/projects/cambodia/vendors/conversion.list.view.tsx
- apps/rahat-ui/src/sections/projects/cambodia/vendors/health.workers.view.tsx
- apps/rahat-ui/src/sections/projects/cambodia/vendors/transaction.history.view.tsx
- apps/rahat-ui/src/sections/projects/cambodia/vendors/vendors.details.tsx
[issue](https://github.com/rahataid/rahat-ui/issues/1297)
> vision centers details crash fix and ui fix

- apps/rahat-ui/src/common/cardSkeleton.tsx
- apps/rahat-ui/src/common/index.ts
- apps/rahat-ui/src/sections/projects/aa-2/communicationLog/details/comms.logs.detail.page.tsx
- apps/rahat-ui/src/sections/projects/aa-2/communicationLog/details/communication.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/communicationLog/main.tsx
- apps/rahat-ui/src/sections/projects/aa-2/communicationLog/table/comms.activities.table.tsx
- apps/rahat-ui/src/sections/projects/aa-2/communicationLog/table/comms.logs.table.tsx
- apps/rahat-ui/src/sections/projects/aa-2/communicationLog/table/useCommsActivitesTableColumns.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dhm/rainfall.monitor.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dhm/rainfall.watch.view.tsx
- libs/query/src/lib/aa/activities/activities.service.ts
- libs/query/src/lib/aa/communication/communication.service.ts
- libs/query/src/lib/aa/stats/stats.service.ts
[issue](https://github.com/rahataid/rahat-project-aa/issues/362)
- filters missing  in which data are not filtered .
- showing all  activity data having comms but not passing the active year and riverBasin  for filtering purpose : 
there  is seprate  action for  rendering the activity data having comms
> comms stats query an integration

- apps/rahat-ui/src/sections/projects/sms-voucher/beneficiary/beneficiary.view.tsx
- apps/rahat-ui/src/sections/vendors/vendors.list.table.tsx
- apps/rahat-ui/src/sections/vendors/vendors.view.tsx
- libs/query/src/lib/vendors/vendors.service.ts
- added vendor filters from server side
> filter vendor from server

- apps/rahat-ui/src/app/projects/aa/[id]/payout/initiate-payout/page.tsx
- apps/rahat-ui/src/app/projects/aa/[id]/payout/list/page.tsx
- apps/rahat-ui/src/app/projects/aa/[id]/payout/page.tsx
- apps/rahat-ui/src/sections/projects/aa-2/payout/component/recent.payment.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/payout/component/recent.payout.tsx
- apps/rahat-ui/src/sections/projects/aa-2/payout/index.ts
- apps/rahat-ui/src/sections/projects/aa-2/payout/initiatePayout/payment.dialog.tsx
- apps/rahat-ui/src/sections/projects/aa-2/payout/initiatePayout/payment.tsx
- apps/rahat-ui/src/sections/projects/aa-2/payout/main.tsx
- apps/rahat-ui/src/sections/projects/aa-2/payout/table/payoutTable.tsx
- apps/rahat-ui/src/sections/projects/aa-2/payout/table/payoutTransactionList.tsx
- apps/rahat-ui/src/sections/projects/aa-2/payout/table/usePayoutTransactionLogTableColumn.tsx
- apps/rahat-ui/src/sections/projects/aa/useAANavItems.tsx
- apps/rahat-ui/src/types/payoutTransactionLog.ts
- libs/shadcn/src/components/charts/chart-components/pie-chart.tsx
[issue](https://github.com/rahataid/rahat-project-aa/issues/366)
> payment initiation

- apps/rahat-ui/src/app/projects/aa/[id]/payout/details/[detailID]/page.tsx
- apps/rahat-ui/src/sections/projects/aa-2/beneficiary/beneficiary.groups.details.tsx
- apps/rahat-ui/src/sections/projects/aa-2/communicationLog/main.tsx
- apps/rahat-ui/src/sections/projects/aa-2/payout/benefGroupDetails/beneficiariesGroupTable.tsx
- apps/rahat-ui/src/sections/projects/aa-2/payout/benefGroupDetails/details.list.tsx
- apps/rahat-ui/src/sections/projects/aa-2/payout/benefGroupDetails/dummy.json
- apps/rahat-ui/src/sections/projects/aa-2/payout/benefGroupDetails/useBeneficiaryGroupDetailsLogColumns.tsx
- apps/rahat-ui/src/sections/projects/aa-2/payout/component/recent.payout.tsx
- apps/rahat-ui/src/sections/projects/aa-2/payout/index.ts
- apps/rahat-ui/src/sections/projects/aa-2/payout/initiatePayout/beneficiariesGroupTable.tsx
- apps/rahat-ui/src/sections/projects/aa-2/payout/initiatePayout/payment.dialog.tsx
- apps/rahat-ui/src/sections/projects/aa-2/payout/initiatePayout/payment.tsx
- apps/rahat-ui/src/sections/projects/aa-2/payout/initiatePayout/useBeneficiariesGroupTablecolumn.tsx
- apps/rahat-ui/src/sections/projects/aa-2/payout/table/dummyTransaction.json
- apps/rahat-ui/src/sections/projects/aa-2/payout/table/usePayoutTransactionLogTableColumn.tsx
- apps/rahat-ui/src/sections/projects/aa-2/stakeholders/StakeholderGroups.tsx
- libs/query/src/lib/aa/groups/groups.service.ts
[issue](https://github.com/rahataid/rahat-project-aa/issues/373)
> redesign ui and integrate required beneficiaries service

- apps/rahat-ui/src/components/datePickerRange.tsx
- apps/rahat-ui/src/sections/chart-reports/datacard-wrapper.tsx
- apps/rahat-ui/src/sections/projects/cambodia/beneficiary/beneficiary.view.tsx
- apps/rahat-ui/src/sections/projects/cambodia/communication/comms.view.tsx
- apps/rahat-ui/src/sections/projects/cambodia/project.detail.tsx
- apps/rahat-ui/src/sections/projects/cambodia/vendors/health.workers.view.tsx
- apps/rahat-ui/src/sections/projects/cambodia/vendors/use.conversion.list.table.columns.tsx
- apps/rahat-ui/src/sections/projects/cambodia/vendors/use.health.workers.table.columns.tsx
- apps/rahat-ui/src/sections/projects/cambodia/vendors/use.transaction.history.table.columns.tsx
- apps/rahat-ui/src/sections/projects/cambodia/vendors/vendors.details.tsx
- libs/query/src/lib/projects/projects.service.ts
- pnpm-lock.yaml
[issue](https://github.com/rahataid/rahat-ui/issues/1310)
> resolved the feedback  of the cambodia stage

- apps/rahat-ui/src/components/datePickerRange.tsx
- apps/rahat-ui/src/sections/chart-reports/datacard-wrapper.tsx
- apps/rahat-ui/src/sections/projects/cambodia/beneficiary/beneficiary.view.tsx
- apps/rahat-ui/src/sections/projects/cambodia/communication/comms.view.tsx
- apps/rahat-ui/src/sections/projects/cambodia/project.detail.tsx
- apps/rahat-ui/src/sections/projects/cambodia/vendors/health.workers.view.tsx
- apps/rahat-ui/src/sections/projects/cambodia/vendors/use.conversion.list.table.columns.tsx
- apps/rahat-ui/src/sections/projects/cambodia/vendors/use.health.workers.table.columns.tsx
- apps/rahat-ui/src/sections/projects/cambodia/vendors/use.transaction.history.table.columns.tsx
- apps/rahat-ui/src/sections/projects/cambodia/vendors/vendors.details.tsx
- libs/query/src/lib/projects/projects.service.ts
- pnpm-lock.yaml
> Sync cam-ken_merge with cambodia-stage 

- apps/rahat-ui/src/sections/projects/cambodia/communication/comms.view.tsx
- apps/rahat-ui/src/sections/projects/cambodia/vendors/use.conversion.list.table.columns.tsx
- apps/rahat-ui/src/sections/projects/cambodia/vendors/use.health.workers.table.columns.tsx
- apps/rahat-ui/src/sections/projects/cambodia/vendors/use.transaction.history.table.columns.tsx
- pnpm-lock.yaml
[issue](https://github.com/rahataid/rahat-ui/issues/1314)
> Enable download features and  checkbox timeout enchance

- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/beneficiary.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/communication/communication.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/communication/sms.detail.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/offline-management/use.beneficiary.table.columns.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/offline-management/use.table.columns.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/select.component.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/transactions/use.transactions.table.columns.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vendors/vendors.beneficiary.list.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vendors/vendors.transactions.history.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vouchers/beneficiary.groups.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vouchers/beneficiary.view.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vouchers/confirmation.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vouchers/use.beneficiary.table.columns.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vouchers/vouchers.manage.tsx
- apps/rahat-ui/src/sections/projects/el-kenya/vouchers/vouchers.view.tsx
> sync dev with ck main

- apps/rahat-ui/src/common/transaction.card.tsx
- apps/rahat-ui/src/hooks/useCopy.ts
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dhm/river.watch.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/fundManagement/assign.funds.tsx
- apps/rahat-ui/src/sections/projects/aa-2/fundManagement/columns/useFMColumns.tsx
- apps/rahat-ui/src/sections/projects/aa-2/fundManagement/columns/useFMDetailColumns.tsx
- apps/rahat-ui/src/sections/projects/aa-2/fundManagement/components/assign.funds.form.tsx
- apps/rahat-ui/src/sections/projects/aa-2/fundManagement/components/tabs.tsx
- apps/rahat-ui/src/sections/projects/aa-2/fundManagement/components/token.overview.skeleton.tsx
- apps/rahat-ui/src/sections/projects/aa-2/fundManagement/components/token.overview.tsx
- apps/rahat-ui/src/sections/projects/aa-2/fundManagement/tables/fm.detail.table.tsx
- apps/rahat-ui/src/sections/projects/aa-2/fundManagement/tables/fm.table.tsx
- apps/rahat-ui/src/sections/projects/aa-2/fundManagement/types/index.ts
- libs/query/src/lib/aa/funManagement/index.ts
- libs/query/src/lib/aa/funManagement/service.ts
- libs/query/src/lib/aa/funManagement/store.ts
- libs/query/src/lib/aa/groups/groups.store.ts
- libs/query/src/lib/aa/index.ts
- libs/query/src/lib/projects/projects.service.ts
[issue](https://github.com/rahataid/rahat-project-aa/issues/454)
[issue2](https://github.com/rahataid/rahat-project-aa/issues/462)
[issue3](https://github.com/rahataid/rahat-project-aa/issues/467)
> fixes on fund management

- apps/rahat-ui/src/sections/projects/aa-2/fundManagement/components/token.overview.skeleton.tsx
- apps/rahat-ui/src/sections/projects/aa-2/vendor/columns/useVendorColumns.tsx
- apps/rahat-ui/src/sections/projects/aa-2/vendor/components/profile.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/vendor/components/transaction.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/vendor/detail.tsx
- apps/rahat-ui/src/sections/projects/aa-2/vendor/main.tsx
- apps/rahat-ui/src/sections/projects/aa-2/vendor/tables/beneficiary.table.tsx
- apps/rahat-ui/src/sections/projects/aa-2/vendor/tables/transactions.history.tsx
- libs/query/src/lib/aa/index.ts
- libs/query/src/lib/aa/vendors/index.ts
- libs/query/src/lib/aa/vendors/store.ts
- libs/query/src/lib/aa/vendors/vendors.service.ts
[issue](https://github.com/rahataid/rahat-project-aa/issues/469)
> vendor list integration and details responsive

- apps/rahat-ui/src/common/back.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dhm/info.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dhm/river.watch.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/add.trigger.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/automated.trigger.add.form.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/edit.tsx
https://github.com/rahataid/rahat-project-aa/issues/435
> AA: Resolve Feedback

- apps/rahat-ui/src/app/projects/aa/[id]/data-sources/daily-monitoring/[monitoringId]/edit/page.tsx
- apps/rahat-ui/src/app/projects/aa/[id]/data-sources/daily-monitoring/[monitoringId]/page.tsx
- apps/rahat-ui/src/common/client.side.pagination.tsx
- apps/rahat-ui/src/common/noResults.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/add/add.another.data.source.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/details/daily.monitoring.detail.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/details/data.source.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/details/dhm/dhm.content.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/details/dhm/monitorig.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/details/dhm/useForcastData.ts
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/details/field.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/details/field.sub.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/details/flash-flood-risk-monitoring/flash.flood.risk.monitoring.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/details/gaugeReading/gaugeReading.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/details/glofas/glofas.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/details/ncmrwf/ncmrwf.accumulated.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/details/ncmrwf/ncmwrf.deterministic.problastic.weatherCard.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/edit/edit.daily.monitoring.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/index.ts
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/list/daily.monitoring.list.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/list/daily.monitoring.table.filters.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/list/daily.monitoring.table.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/useDailyMonitoringTableColumn.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/useSelectItems.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/index.ts
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/main.tsx
- libs/query/src/lib/aa/daily-monitoring/daily-monitoring.service.ts
[issue](https://github.com/rahataid/rahat-project-aa/issues/481)
> listing integration and edit page design and integration  of daily monitoring

- apps/rahat-ui/src/app/projects/aa/[id]/data-sources/daily-monitoring/[monitoringId]/edit/page.tsx
- apps/rahat-ui/src/app/projects/aa/[id]/data-sources/daily-monitoring/[monitoringId]/page.tsx
- apps/rahat-ui/src/common/client.side.pagination.tsx
- apps/rahat-ui/src/common/noResults.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/add/add.another.data.source.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/details/daily.monitoring.detail.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/details/data.source.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/details/dhm/dhm.content.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/details/dhm/monitorig.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/details/dhm/useForcastData.ts
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/details/field.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/details/field.sub.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/details/flash-flood-risk-monitoring/flash.flood.risk.monitoring.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/details/gaugeReading/gaugeReading.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/details/glofas/glofas.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/details/ncmrwf/ncmrwf.accumulated.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/details/ncmrwf/ncmwrf.deterministic.problastic.weatherCard.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/edit/edit.daily.monitoring.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/index.ts
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/list/daily.monitoring.list.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/list/daily.monitoring.table.filters.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/list/daily.monitoring.table.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/useDailyMonitoringTableColumn.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/useSelectItems.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/index.ts
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/main.tsx
- libs/query/src/lib/aa/daily-monitoring/daily-monitoring.service.ts
> sync stage with dev

- apps/rahat-ui/src/common/back.tsx
- apps/rahat-ui/src/common/custom.pagination.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/components/documentCard.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/details/activity.detail.cards.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/details/activity.detail.page.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/list/activities.list.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/list/activities.table.tsx
- apps/rahat-ui/src/sections/projects/aa-2/communicationLog/components/commsShartsStats.tsx
- apps/rahat-ui/src/sections/projects/aa-2/communicationLog/components/commsSkeleton.tsx
- apps/rahat-ui/src/sections/projects/aa-2/communicationLog/main.tsx
- apps/rahat-ui/src/sections/projects/aa-2/communicationLog/table/comms.activities.table.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/add/add.another.data.source.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/add/add.daily.monitoring.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/details/daily.monitoring.detail.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/details/gaugeReading/gaugeReading.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/edit/edit.daily.monitoring.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/useSelectItems.tsx
[issue1](https://github.com/rahataid/rahat-project-aa/issues/485)
[issue2](https://github.com/rahataid/rahat-project-aa/issues/486)
> Activities details mobile responsive

- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/add.trigger.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/automated.trigger.add.form.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/detail.forecast.data.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/edit.tsx
https://github.com/rahataid/rahat-project-aa/issues/482
> AA: Daily monitoring in triggers

- apps/rahat-ui/src/sections/projects/aa-2/activities/details/activity.detail.cards.tsx
- apps/rahat-ui/src/sections/projects/aa-2/beneficiary/beneficiary.groups.details.tsx
- apps/rahat-ui/src/sections/projects/aa-2/beneficiary/beneficiary.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/beneficiary/columns.tsx
- apps/rahat-ui/src/sections/projects/aa-2/communicationLog/components/commsShartsStats.tsx
- apps/rahat-ui/src/sections/projects/aa-2/communicationLog/components/commsSkeleton.tsx
- apps/rahat-ui/src/sections/projects/aa-2/communicationLog/details/view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/communicationLog/main.tsx
- apps/rahat-ui/src/sections/projects/aa-2/communicationLog/table/useCommsLogsTableColumns.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/list/daily.monitoring.list.view.tsx
- libs/query/src/lib/aa/stats/stats.service.ts
[issue](https://github.com/rahataid/rahat-project-aa/issues/499)
> Bug fix & comms integration

- .github/workflows/AA-Stage-v2.yaml
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/add/add.daily.monitoring.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/list/daily.monitoring.list.view.tsx
- pnpm-lock.yaml
conflict arrived while merging this branch is here to solve the conflict between the  integration-aa-triggers and dev v-2 branch
> resolved the conflict while merging the base branch(integration) to dev  v2 branch

- apps/rahat-ui/src/common/custom.alert.dialog.tsx
- apps/rahat-ui/src/common/icon.label.btn.tsx
- apps/rahat-ui/src/common/index.ts
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/dynamic.triggers.list.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/trigger.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/triggers.list.tabs.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/phase.detail.tsx
- libs/query/src/lib/aa/phases/phases.service.ts
- libs/shadcn/src/components/ui/alert-dialog.tsx
https://github.com/rahataid/rahat-project-aa/issues/529
> AA: Revert phase

- apps/rahat-ui/src/sections/projects/aa-2/activities/add/add.activity.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/add/add.communication.form.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/list/daily.monitoring.list.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/stakeholders/add.stakeholder.groups.tsx
- apps/rahat-ui/src/sections/projects/aa-2/stakeholders/add.stakeholders.tsx
- apps/rahat-ui/src/sections/projects/aa-2/stakeholders/import.stakeholders.tsx
https://github.com/rahataid/rahat-project-aa/issues/403
https://github.com/rahataid/rahat-project-aa/issues/504
https://github.com/rahataid/rahat-project-aa/issues/509
https://github.com/rahataid/rahat-project-aa/issues/543
https://github.com/rahataid/rahat-project-aa/issues/503
https://github.com/rahataid/rahat-project-aa/issues/517
https://github.com/rahataid/rahat-project-aa/issues/542
> Fixed bugs and feedback

- apps/rahat-ui/src/sections/projects/aa-2/activities/components/phase-content.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/details/update.activity.status.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/list/activities.list.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/list/useActivitiesTableColumn.tsx
https://github.com/orgs/rahataid/projects/51/views/6?filterQuery=assignee%3A%40me&pane=issue&itemId=113052216&issue=rahataid%7Crahat-project-aa%7C551
> 551 add update status icon in activities table with redirect functionality

- apps/rahat-ui/src/sections/projects/c2c/transactions/transactions.view.tsx
- apps/rahat-ui/src/sections/projects/c2c/transactions/useTransactionColumn.tsx
> fix:added timestamp sorting

- apps/rahat-ui/src/app/projects/aa/[id]/phase/[phaseId]/config-threshold/page.tsx
- apps/rahat-ui/src/common/page.heading.tsx
- apps/rahat-ui/src/common/transaction.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/fundManagement/components/assign.funds.form.tsx
- apps/rahat-ui/src/sections/projects/aa-2/fundManagement/components/token.overview.tsx
- apps/rahat-ui/src/sections/projects/aa-2/fundManagement/details.tsx
- apps/rahat-ui/src/sections/projects/aa-2/fundManagement/tables/fm.detail.table.tsx
- apps/rahat-ui/src/sections/projects/aa-2/fundManagement/tables/fm.table.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/index.ts
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/manage.threshold.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/phase.detail.tsx
- libs/query/src/lib/aa/phases/phases.service.ts
- libs/query/src/lib/aa/phases/phases.store.ts
https://github.com/rahataid/rahat-project-aa/issues/571
https://github.com/rahataid/rahat-project-aa/issues/546
> Fundmanagement feedback features acitivity features

- apps/rahat-ui/src/sections/projects/aa-2/fundManagement/components/assign.funds.form.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/manage.threshold.tsx
https://github.com/rahataid/rahat-project-aa/issues/579
>  validate form in manage threshold and  assign  fund page

- apps/rahat-ui/src/common/icon.label.btn.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/add/add.activity.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/add/add.communication.form.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/add/add.communicationDataCard.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/details/dialog.reuse.tsx
- Disabled the "Save" button while the communication form is open to prevent accidental submission before filling required fields.<img width="990" alt="Screenshot 1947-03-15 at 11 07 20 PM" src="https://github.com/user-attachments/assets/26345d47-f55c-4cdb-80ac-1402bf771296" />
> fix: disable save button when communication from is open

- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/phase.detail.tsx
https://github.com/orgs/rahataid/projects/51/views/6?filterQuery=assignee%3A%40me&pane=issue&itemId=114342055&issue=rahataid%7Crahat-project-aa%7C585
- this ui is displayed when triggered
> 585-once phase is triggered it should show warning signnotification with timestamp add time also if applicable

- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/add/add.another.data.source.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/list/daily.monitoring.table.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dhm/info.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dhm/river.watch.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dhm/table.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/glofas/glofas.info.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/glofas/glofas.section.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/glofas/index.ts
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/index.ts
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/main.tsx
- libs/query/src/lib/aa/trigger-statements/trigger-statements.service.ts
- package.json
https://github.com/rahataid/rahat-project-aa/issues/560
https://github.com/rahataid/rahat-project-aa/issues/581
> AA: Forecast >> Glofas + Bug Fixes

- apps/rahat-ui/src/sections/projects/aa-2/activities/add/add.activity.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/details/update.activity.status.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/edit/activity.edit.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/list/useActivitiesTableColumn.tsx
- apps/rahat-ui/src/sections/projects/aa-2/communicationLog/table/useCommsActivitesTableColumns.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/useDailyMonitoringTableColumn.tsx
- apps/rahat-ui/src/sections/projects/aa-2/fundManagement/columns/useFMColumns.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/activate.trigger.dialog.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/automated.trigger.add.form.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/dynamic.triggers.list.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/trigger.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/triggers.list.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/triggers.list.tabs.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/detail.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/edit.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/phase.detail.tsx
- apps/rahat-ui/src/utils/file.validation.ts
- libs/query/src/lib/aa/phases/phases.service.ts
- libs/query/src/lib/aa/trigger-statements/trigger-statements.service.ts
https://github.com/rahataid/rahat-project-aa/issues/589
> integration of revert phase get one and implementation and bug fix

- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/triggers.phase.card.tsx
> fix: typo and color in TriggersPhaseCard

- apps/rahat-ui/src/common/page.heading.tsx
- apps/rahat-ui/src/sections/projects/aa/useAANavItems.tsx
- apps/rahat-ui/src/sidebar-components/nav-main.tsx
- libs/query/src/lib/aa/phases/phases.service.ts
- libs/query/src/lib/aa/trigger-statements/trigger-statements.service.ts
https://github.com/rahataid/rahat-project-aa/issues/609
https://github.com/rahataid/rahat-project-aa/issues/591
https://github.com/rahataid/rahat-project-aa/issues/329
- Responsive page heading
> AA: Bug fixes

- apps/rahat-ui/src/sections/beneficiary/groups/removeGroupModal.tsx
- libs/query/src/lib/beneficiary/beneficiary.service.ts
https://github.com/orgs/rahataid/projects/51/views/6?filterQuery=assignee%3A%40me&pane=issue&itemId=116551806&issue=rahataid%7Crahat-project-aa%7C642
> fix: Integrated group delete func in UI

- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/add/add.daily.monitoring.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/select.form.field.tsx
- libs/query/src/lib/aa/phases/phases.service.ts
https://github.com/rahataid/rahat-project-aa/issues/631
> AA: Dynamic river basin dropdown

- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/triggers.phase.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/detail.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/phase.detail.tsx
https://github.com/orgs/rahataid/projects/51/views/26?pane=issue&itemId=116510551&issue=rahataid%7Crahat-project-aa%7C639
- Added new field: `createdBy` on trigger details page
- Disabled delete and edit buttons when phase is active
- Hid trigger button when phase is active
- Disabled "Add Trigger" button when phase is active
- Updated badge color on trigger details page based on phase name
> 639 trigger statement feedbacks

- apps/rahat-ui/src/sections/projects/aa-2/activities/add/add.communication.form.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/components/recorder.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/edit/edit.communication.form.tsx
Voice Recording Functionality (IVR) in the add activity and edit page
https://github.com/rahataid/rahat-project-aa/issues/657
> audio record features implementation

- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dhm/chart.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dhm/table.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/glofas/glofas.info.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/river.watch.details.tsx
https://github.com/rahataid/rahat-project-aa/issues/659
> AA: Fix forecast section issues

- apps/rahat-ui/src/sections/beneficiary/groups/groups.detail.tsx
- apps/rahat-ui/src/sections/beneficiary/groups/members.table.tsx
https://github.com/rahataid/rahat-project-aa/issues/710
> AA: Fix Core Grouped Benfs Pagination

- apps/rahat-ui/src/app/projects/aa/[id]/trigger-statements/[triggerID]/edit/page.tsx
- apps/rahat-ui/src/app/projects/aa/[id]/trigger-statements/add/page.tsx
- apps/rahat-ui/src/app/projects/aa/[id]/trigger-statements/phase/[phaseId]/config-threshold/page.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/triggers.phase.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/detail.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/phase.detail.tsx
Restricted manager role for C U D operations in triggers section
> Roles auth update for manager role in triggers section

- apps/rahat-ui/src/sections/beneficiary/beneficiary.layout.tsx
- apps/rahat-ui/src/sections/beneficiary/beneficiaryDetail.tsx
- apps/rahat-ui/src/sections/projects/aa-2/payout/benefGroupDetails/beneficiariesGroupTable.tsx
- apps/rahat-ui/src/sections/projects/aa-2/payout/benefGroupDetails/details.list.tsx
- apps/rahat-ui/src/sections/users/user.layout.tsx
- apps/rahat-ui/src/sections/vendors/vendors.layout.tsx
https://github.com/rahataid/rahat-project-aa/issues/743
https://github.com/rahataid/rahat-project-aa/issues/750
> feedback on the core and project 

- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dhm/info.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dhm/rainfall.monitor.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dhm/rainfall.watch.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dhm/river.watch.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dhm/water.level.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/river.watch.details.tsx
https://github.com/rahataid/rahat-project-aa/issues/656
> AA: Apply dhm data modification

- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/activate.trigger.dialog.tsx
fix: resolve error message when active triggers lack notes data
> Triggers notes Error

- apps/rahat-ui/src/sections/projects/aa-2/vendor/columns/useBeneficiaryColumns.tsx
- apps/rahat-ui/src/sections/projects/aa-2/vendor/columns/useTransactionColumns.tsx
- apps/rahat-ui/src/sections/projects/aa-2/vendor/components/overview.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/vendor/components/profile.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/vendor/detail.tsx
- apps/rahat-ui/src/sections/projects/aa-2/vendor/table.columns.tsx
- apps/rahat-ui/src/sections/projects/aa-2/vendor/tables/beneficiary.table.tsx
- apps/rahat-ui/src/utils/string.ts
- libs/query/src/lib/aa/vendors/vendors.service.ts
- Vendor details API integration
- Vendor oflfine beneficiaries API integration
> Vendor beneficiaries api integration

- apps/rahat-ui/src/components/infoModal.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dhm/chart.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/gfh/gfhCard.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/gfh/index.tsx
- apps/rahat-ui/src/sections/projects/aa-2/dataSources/main.tsx
- libs/query/src/lib/aa/trigger-statements/trigger-statements.service.ts
https://github.com/rahataid/rahat-project-aa/issues/742
1. Integrated waterLevels.getGfh API to fetch water level data.
2. Display data in the UI with:
- Loading state
- Error handling
- Empty state message
1. Updated the chart component to:
- Accept extremeLevel as a prop
- Support customizable dateFormat (e.g., M/D format)
> Implement water level data fetching and UI state handling using waterLevels.getGfh API

- apps/rahat-ui/src/sections/projects/el-kenya/beneficiary/beneficiary.view.tsx
- libs/query/src/lib/projects/projects.service.ts
> Sync with stage

- apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/gfh/index.tsx
- changed date formate 7/21 to july 21
> 742 forecast data enhancement add google flood hub tab

- apps/rahat-ui/src/sections/projects/aa-2/activities/details/update.activity.status.tsx
- libs/query/src/lib/aa/activities/activities.service.ts
https://github.com/orgs/rahataid/projects/51/views/6?filterQuery=assignee%3A%40me&pane=issue&itemId=114545044&issue=rahataid%7Crahat-project-aa%7C593
> 593 optimization enhance system performance and efficiency project aa

- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/dynamic.triggers.list.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/trigger.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/triggers.list.card.tsx
- libs/query/src/lib/aa/trigger-statements/trigger-statements.service.ts
https://github.com/orgs/rahataid/projects/51/views/6?filterQuery=assignee%3A%40me&pane=issue&itemId=121125361&issue=rahataid%7Crahat-project-aa%7C761
- Added close(x) button in trigger success message which is shown when manual trigger statement is triggered.
> 761 aa trigger statement feedbacks

- apps/rahat-ui/src/sections/projects/aa-2/activities/components/communicationCard.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/details/activity.detail.cards.tsx
- apps/rahat-ui/src/sections/projects/aa-2/communicationLog/details/comms.logs.detail.page.tsx
- apps/rahat-ui/src/sections/projects/aa-2/communicationLog/details/communication.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/communicationLog/main.tsx
https://github.com/orgs/rahataid/projects/51/views/6?filterQuery=assignee%3A%40me&pane=issue&itemId=122964823&issue=rahataid%7Crahat-project-aa%7C819
https://github.com/orgs/rahataid/projects/51/views/6?filterQuery=assignee%3A%40me&pane=issue&itemId=123905414&issue=rahataid%7Crahat-project-aa%7C848
- displayed completedAt value on Activity details and communication details page.
> display communication completed at in activity details page and communication details page

- apps/rahat-ui/src/sections/projects/aa-2/payout/benefGroupDetails/useBeneficiaryGroupDetailsLogColumns.tsx
- apps/rahat-ui/src/sections/projects/aa-2/payout/benefTransactionDetails/benefTransactionDetails.tsx
- apps/rahat-ui/src/sections/projects/aa-2/payout/component/recent.payment.card.tsx
- apps/rahat-ui/src/sections/projects/aa-2/payout/component/recent.payout.tsx
- libs/query/src/lib/aa/payout/payout.service.ts
https://github.com/rahataid/rahat-project-aa/issues/812
> payout fix

- apps/rahat-ui/src/sections/projects/aa-2/activities/add/add.activity.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/add/add.communication.form.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/add/add.communicationDataCard.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/components/communicationCard.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/details/activity.detail.cards.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/details/activity.detail.page.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/edit/activity.edit.view.tsx
- apps/rahat-ui/src/sections/projects/aa-2/activities/edit/edit.communication.form.tsx
- apps/rahat-ui/src/sections/projects/aa-2/fundManagement/details.tsx
- apps/rahat-ui/src/sections/projects/aa-2/payout/benefGroupDetails/details.list.tsx
- apps/rahat-ui/src/sections/projects/aa-2/payout/benefGroupDetails/useBeneficiaryGroupDetailsLogColumns.tsx
- apps/rahat-ui/src/sections/projects/aa-2/payout/benefTransactionDetails/benefTransactionDetails.tsx
- apps/rahat-ui/src/sections/projects/aa-2/payout/component/recent.payout.tsx
- apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/phase.detail.tsx
- libs/query/src/lib/new-comms/new-comms.query.tsx
> fix(activity): add error for max voice resend attempts & update form with comm title and redirection fix

- apps/rahat-ui/src/components/dialog.tsx
- apps/rahat-ui/src/sections/projects/aa-2/vendor/table.columns.tsx
- apps/rahat-ui/src/sections/projects/aa-2/vendor/tabs/vendor.redemption.list.tsx
https://github.com/rahataid/rahat-project-aa/issues/859
Vendor redemptions list approve confirmation modal added and table UI updates
> Figma UI updates

- apps/rahat-ui/src/app/projects/aa/[id]/fund-management/initiate/page.tsx
- apps/rahat-ui/src/app/projects/aa/[id]/fund-management/page.tsx
- apps/rahat-ui/src/sections/projects/aa-2/fundManagement/components/cashTracker/cash.tracker.tsx
- apps/rahat-ui/src/sections/projects/aa-2/fundManagement/components/cashTracker/initiate.fund.transfer.tsx
- apps/rahat-ui/src/sections/projects/aa/useAANavItems.tsx
- libs/auth/src/enums/aaRoles.ts
- Implemented role base tracking functionality.
- sort transactions history
> role based cash tracker

- apps/rahat-ui/src/sections/projects/aa-2/fundManagement/components/confirmation.tsx
- apps/rahat-ui/src/sections/projects/aa-2/fundManagement/components/errorInfoPopupModel.tsx
- libs/query/src/lib/aa/groups/groups.service.ts
https://github.com/orgs/rahataid/projects/51/views/6?filterQuery=assignee%3A%40me&pane=issue&itemId=122457871&issue=rahataid%7Crahat-project-aa%7C799
> Prevent duplicate fund assignment to same beneficiary across multiple fund assignments

- apps/rahat-ui/src/app/projects/layout.tsx
- apps/rahat-ui/src/components/nav.tsx
- apps/rahat-ui/src/guards/auth-guard.tsx
- apps/rahat-ui/src/sections/projects/components/project-header.tsx
https://github.com/rahataid/rahat-project-aa/issues/901
> redirect to login instead of white screen on logout and direct access to /projects
